---
name: Ranks
author: IvanCraft623
version: 1.0.3
main: IvanCraft623\Ranks\Ranks
api: 3.0.0
depend: [PurePerms]
commands:
  ranks:
    description: "temp ranks command! Plugin by (Twitter: @IvanCraft623)"
permissions:
  ranks.cmd.settemprank:
    description: Use rank settemprank command
  ranks.cmd.createcode:
    description: Use rank createcode command
  ranks.cmd.deletecode:
    description: Use rank deletecode command
  ranks.cmd.manage:
    description: Use rank manage command
...
